### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by goosvorbook** [AlexCouch/JoyCouch#1]
Currently this code has no license, making it unclear how it is supposed to be used, modified and reused. If it is desired that the code be open source and usable by others, then perhaps one of the licenses listed here could be used:

https://opensource.org/licenses

**Comment by AlexCouch** [comment]
I was actually looking at the license not too long ago and thinking that I ought to add one. I am actually planning on migrating to a different workspace for native development in a separate repository. However, I will add a license to this one. Better safe than sorry. Thank you for the list, too!
